version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.5.0-stretch
    steps:
      - checkout

      - run: sudo npm install -g npm@latest

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

      - run: ./cc-test-reporter before-build

      - run: npm test

      - run: ./cc-test-reporter after-build --coverage-input-type icov --exit-code $?
