version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.5.0-stretch
    steps:
      - checkout
      - run: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 'npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 'npm test'
